import { GetStaticProps, InferGetStaticPropsType } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";

import Club from "@/models/club";

const inter = Inter({ subsets: ["latin"] });

export default function Home(
  props: InferGetStaticPropsType<typeof getStaticProps>
) {
  return (
    <>
      <Head>
        <title>Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}></main>
      <pre>{JSON.stringify(props.clubs, null, 2)}</pre>
    </>
  );
}

export const getStaticProps: GetStaticProps = async (context) => {
  const clubs = await Club.find();

  return {
    props: { clubs: JSON.parse(JSON.stringify(clubs)) }, // will be passed to the page component as props
  };
};
