name: Create User

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Full name"
        required: true
      email:
          description: "Email Address"
          required: true
      password:
          description: "Password"
          required: true
      admin:
        description: 'Is this user going to be admin?'
        required: false
        type: boolean
        default: false

jobs:
  create_user:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run new-user ${{ github.event.inputs.name }} ${{ github.event.inputs.email }} ${{ github.event.inputs.password }} ${{ github.event.inputs.admin }}
