name: Hello World

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "What's the name of user?"
        required: true
      admin:
        description: 'Is this user going to be admin?'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm src/utils/createUser.ts
